export const START_API = 'start_api'
export const SET_FAVORITES = 'get_favorites'
export const ADD_FAVORITE = 'add_favorite'
export const DELETE_FAVORITE = 'delete_favorite'
export const ERROR_API = 'error_api'
