name: Food Store Delivery Laravel

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]
    paths:
      - api/

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.2.2'
      - uses: actions/checkout@v3
      - name: Copy .env
        run: cd ./api/ && php -r "file_exists('.env') || copy('.env.example', '.env');"
      - name: Install Dependencies composer.json
        run: cd ./api/ && composer install --optimize-autoloader --no-dev
      - name: Install Dependencies package.json
        run: cd ./api/ && npm install
      - name: Directory Permissions and delete config cache
          run: cd ./api/ && chmod -R 777 storage bootstrap/cache && rm bootstrap/cache/config.php
      - name: Generate key
        run: cd ./api/ && php artisan key:generate
      - name: Config cache
        run: cd ./api/ && php artisan config:cache
      - name: route cache
        run: cd ./api/ && php artisan route:cache
      - name: Optimize cache
        run: cd ./api/ && php artisan optimize:clear
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: /
