name: Food Store Delivery React

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]
    paths:
      - 'client/'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deplying to surge

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.14.2'
      - run: cd ./client/ && npm i -g surge
      - run: surge ./client ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}